# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/martin/wmfs

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/martin/wmfs

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/martin/wmfs/CMakeFiles /home/martin/wmfs/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/martin/wmfs/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named wmfs

# Build rule for target.
wmfs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wmfs
.PHONY : wmfs

# fast build rule for target.
wmfs/fast:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/build
.PHONY : wmfs/fast

src/barwin.o: src/barwin.c.o
.PHONY : src/barwin.o

# target to build an object file
src/barwin.c.o:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/barwin.c.o
.PHONY : src/barwin.c.o

src/barwin.i: src/barwin.c.i
.PHONY : src/barwin.i

# target to preprocess a source file
src/barwin.c.i:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/barwin.c.i
.PHONY : src/barwin.c.i

src/barwin.s: src/barwin.c.s
.PHONY : src/barwin.s

# target to generate assembly for a file
src/barwin.c.s:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/barwin.c.s
.PHONY : src/barwin.c.s

src/cfactor.o: src/cfactor.c.o
.PHONY : src/cfactor.o

# target to build an object file
src/cfactor.c.o:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/cfactor.c.o
.PHONY : src/cfactor.c.o

src/cfactor.i: src/cfactor.c.i
.PHONY : src/cfactor.i

# target to preprocess a source file
src/cfactor.c.i:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/cfactor.c.i
.PHONY : src/cfactor.c.i

src/cfactor.s: src/cfactor.c.s
.PHONY : src/cfactor.s

# target to generate assembly for a file
src/cfactor.c.s:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/cfactor.c.s
.PHONY : src/cfactor.c.s

src/client.o: src/client.c.o
.PHONY : src/client.o

# target to build an object file
src/client.c.o:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/client.c.o
.PHONY : src/client.c.o

src/client.i: src/client.c.i
.PHONY : src/client.i

# target to preprocess a source file
src/client.c.i:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/client.c.i
.PHONY : src/client.c.i

src/client.s: src/client.c.s
.PHONY : src/client.s

# target to generate assembly for a file
src/client.c.s:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/client.c.s
.PHONY : src/client.c.s

src/color.o: src/color.c.o
.PHONY : src/color.o

# target to build an object file
src/color.c.o:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/color.c.o
.PHONY : src/color.c.o

src/color.i: src/color.c.i
.PHONY : src/color.i

# target to preprocess a source file
src/color.c.i:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/color.c.i
.PHONY : src/color.c.i

src/color.s: src/color.c.s
.PHONY : src/color.s

# target to generate assembly for a file
src/color.c.s:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/color.c.s
.PHONY : src/color.c.s

src/config.o: src/config.c.o
.PHONY : src/config.o

# target to build an object file
src/config.c.o:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/config.c.o
.PHONY : src/config.c.o

src/config.i: src/config.c.i
.PHONY : src/config.i

# target to preprocess a source file
src/config.c.i:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/config.c.i
.PHONY : src/config.c.i

src/config.s: src/config.c.s
.PHONY : src/config.s

# target to generate assembly for a file
src/config.c.s:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/config.c.s
.PHONY : src/config.c.s

src/draw.o: src/draw.c.o
.PHONY : src/draw.o

# target to build an object file
src/draw.c.o:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/draw.c.o
.PHONY : src/draw.c.o

src/draw.i: src/draw.c.i
.PHONY : src/draw.i

# target to preprocess a source file
src/draw.c.i:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/draw.c.i
.PHONY : src/draw.c.i

src/draw.s: src/draw.c.s
.PHONY : src/draw.s

# target to generate assembly for a file
src/draw.c.s:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/draw.c.s
.PHONY : src/draw.c.s

src/event.o: src/event.c.o
.PHONY : src/event.o

# target to build an object file
src/event.c.o:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/event.c.o
.PHONY : src/event.c.o

src/event.i: src/event.c.i
.PHONY : src/event.i

# target to preprocess a source file
src/event.c.i:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/event.c.i
.PHONY : src/event.c.i

src/event.s: src/event.c.s
.PHONY : src/event.s

# target to generate assembly for a file
src/event.c.s:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/event.c.s
.PHONY : src/event.c.s

src/ewmh.o: src/ewmh.c.o
.PHONY : src/ewmh.o

# target to build an object file
src/ewmh.c.o:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/ewmh.c.o
.PHONY : src/ewmh.c.o

src/ewmh.i: src/ewmh.c.i
.PHONY : src/ewmh.i

# target to preprocess a source file
src/ewmh.c.i:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/ewmh.c.i
.PHONY : src/ewmh.c.i

src/ewmh.s: src/ewmh.c.s
.PHONY : src/ewmh.s

# target to generate assembly for a file
src/ewmh.c.s:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/ewmh.c.s
.PHONY : src/ewmh.c.s

src/frame.o: src/frame.c.o
.PHONY : src/frame.o

# target to build an object file
src/frame.c.o:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/frame.c.o
.PHONY : src/frame.c.o

src/frame.i: src/frame.c.i
.PHONY : src/frame.i

# target to preprocess a source file
src/frame.c.i:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/frame.c.i
.PHONY : src/frame.c.i

src/frame.s: src/frame.c.s
.PHONY : src/frame.s

# target to generate assembly for a file
src/frame.c.s:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/frame.c.s
.PHONY : src/frame.c.s

src/infobar.o: src/infobar.c.o
.PHONY : src/infobar.o

# target to build an object file
src/infobar.c.o:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/infobar.c.o
.PHONY : src/infobar.c.o

src/infobar.i: src/infobar.c.i
.PHONY : src/infobar.i

# target to preprocess a source file
src/infobar.c.i:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/infobar.c.i
.PHONY : src/infobar.c.i

src/infobar.s: src/infobar.c.s
.PHONY : src/infobar.s

# target to generate assembly for a file
src/infobar.c.s:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/infobar.c.s
.PHONY : src/infobar.c.s

src/init.o: src/init.c.o
.PHONY : src/init.o

# target to build an object file
src/init.c.o:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/init.c.o
.PHONY : src/init.c.o

src/init.i: src/init.c.i
.PHONY : src/init.i

# target to preprocess a source file
src/init.c.i:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/init.c.i
.PHONY : src/init.c.i

src/init.s: src/init.c.s
.PHONY : src/init.s

# target to generate assembly for a file
src/init.c.s:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/init.c.s
.PHONY : src/init.c.s

src/launcher.o: src/launcher.c.o
.PHONY : src/launcher.o

# target to build an object file
src/launcher.c.o:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/launcher.c.o
.PHONY : src/launcher.c.o

src/launcher.i: src/launcher.c.i
.PHONY : src/launcher.i

# target to preprocess a source file
src/launcher.c.i:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/launcher.c.i
.PHONY : src/launcher.c.i

src/launcher.s: src/launcher.c.s
.PHONY : src/launcher.s

# target to generate assembly for a file
src/launcher.c.s:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/launcher.c.s
.PHONY : src/launcher.c.s

src/layout.o: src/layout.c.o
.PHONY : src/layout.o

# target to build an object file
src/layout.c.o:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/layout.c.o
.PHONY : src/layout.c.o

src/layout.i: src/layout.c.i
.PHONY : src/layout.i

# target to preprocess a source file
src/layout.c.i:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/layout.c.i
.PHONY : src/layout.c.i

src/layout.s: src/layout.c.s
.PHONY : src/layout.s

# target to generate assembly for a file
src/layout.c.s:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/layout.c.s
.PHONY : src/layout.c.s

src/menu.o: src/menu.c.o
.PHONY : src/menu.o

# target to build an object file
src/menu.c.o:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/menu.c.o
.PHONY : src/menu.c.o

src/menu.i: src/menu.c.i
.PHONY : src/menu.i

# target to preprocess a source file
src/menu.c.i:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/menu.c.i
.PHONY : src/menu.c.i

src/menu.s: src/menu.c.s
.PHONY : src/menu.s

# target to generate assembly for a file
src/menu.c.s:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/menu.c.s
.PHONY : src/menu.c.s

src/mouse.o: src/mouse.c.o
.PHONY : src/mouse.o

# target to build an object file
src/mouse.c.o:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/mouse.c.o
.PHONY : src/mouse.c.o

src/mouse.i: src/mouse.c.i
.PHONY : src/mouse.i

# target to preprocess a source file
src/mouse.c.i:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/mouse.c.i
.PHONY : src/mouse.c.i

src/mouse.s: src/mouse.c.s
.PHONY : src/mouse.s

# target to generate assembly for a file
src/mouse.c.s:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/mouse.c.s
.PHONY : src/mouse.c.s

src/parse.o: src/parse.c.o
.PHONY : src/parse.o

# target to build an object file
src/parse.c.o:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/parse.c.o
.PHONY : src/parse.c.o

src/parse.i: src/parse.c.i
.PHONY : src/parse.i

# target to preprocess a source file
src/parse.c.i:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/parse.c.i
.PHONY : src/parse.c.i

src/parse.s: src/parse.c.s
.PHONY : src/parse.s

# target to generate assembly for a file
src/parse.c.s:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/parse.c.s
.PHONY : src/parse.c.s

src/parse_api.o: src/parse_api.c.o
.PHONY : src/parse_api.o

# target to build an object file
src/parse_api.c.o:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/parse_api.c.o
.PHONY : src/parse_api.c.o

src/parse_api.i: src/parse_api.c.i
.PHONY : src/parse_api.i

# target to preprocess a source file
src/parse_api.c.i:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/parse_api.c.i
.PHONY : src/parse_api.c.i

src/parse_api.s: src/parse_api.c.s
.PHONY : src/parse_api.s

# target to generate assembly for a file
src/parse_api.c.s:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/parse_api.c.s
.PHONY : src/parse_api.c.s

src/screen.o: src/screen.c.o
.PHONY : src/screen.o

# target to build an object file
src/screen.c.o:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/screen.c.o
.PHONY : src/screen.c.o

src/screen.i: src/screen.c.i
.PHONY : src/screen.i

# target to preprocess a source file
src/screen.c.i:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/screen.c.i
.PHONY : src/screen.c.i

src/screen.s: src/screen.c.s
.PHONY : src/screen.s

# target to generate assembly for a file
src/screen.c.s:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/screen.c.s
.PHONY : src/screen.c.s

src/split.o: src/split.c.o
.PHONY : src/split.o

# target to build an object file
src/split.c.o:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/split.c.o
.PHONY : src/split.c.o

src/split.i: src/split.c.i
.PHONY : src/split.i

# target to preprocess a source file
src/split.c.i:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/split.c.i
.PHONY : src/split.c.i

src/split.s: src/split.c.s
.PHONY : src/split.s

# target to generate assembly for a file
src/split.c.s:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/split.c.s
.PHONY : src/split.c.s

src/status.o: src/status.c.o
.PHONY : src/status.o

# target to build an object file
src/status.c.o:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/status.c.o
.PHONY : src/status.c.o

src/status.i: src/status.c.i
.PHONY : src/status.i

# target to preprocess a source file
src/status.c.i:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/status.c.i
.PHONY : src/status.c.i

src/status.s: src/status.c.s
.PHONY : src/status.s

# target to generate assembly for a file
src/status.c.s:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/status.c.s
.PHONY : src/status.c.s

src/systray.o: src/systray.c.o
.PHONY : src/systray.o

# target to build an object file
src/systray.c.o:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/systray.c.o
.PHONY : src/systray.c.o

src/systray.i: src/systray.c.i
.PHONY : src/systray.i

# target to preprocess a source file
src/systray.c.i:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/systray.c.i
.PHONY : src/systray.c.i

src/systray.s: src/systray.c.s
.PHONY : src/systray.s

# target to generate assembly for a file
src/systray.c.s:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/systray.c.s
.PHONY : src/systray.c.s

src/tag.o: src/tag.c.o
.PHONY : src/tag.o

# target to build an object file
src/tag.c.o:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/tag.c.o
.PHONY : src/tag.c.o

src/tag.i: src/tag.c.i
.PHONY : src/tag.i

# target to preprocess a source file
src/tag.c.i:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/tag.c.i
.PHONY : src/tag.c.i

src/tag.s: src/tag.c.s
.PHONY : src/tag.s

# target to generate assembly for a file
src/tag.c.s:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/tag.c.s
.PHONY : src/tag.c.s

src/util.o: src/util.c.o
.PHONY : src/util.o

# target to build an object file
src/util.c.o:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/util.c.o
.PHONY : src/util.c.o

src/util.i: src/util.c.i
.PHONY : src/util.i

# target to preprocess a source file
src/util.c.i:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/util.c.i
.PHONY : src/util.c.i

src/util.s: src/util.c.s
.PHONY : src/util.s

# target to generate assembly for a file
src/util.c.s:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/util.c.s
.PHONY : src/util.c.s

src/viwmfs.o: src/viwmfs.c.o
.PHONY : src/viwmfs.o

# target to build an object file
src/viwmfs.c.o:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/viwmfs.c.o
.PHONY : src/viwmfs.c.o

src/viwmfs.i: src/viwmfs.c.i
.PHONY : src/viwmfs.i

# target to preprocess a source file
src/viwmfs.c.i:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/viwmfs.c.i
.PHONY : src/viwmfs.c.i

src/viwmfs.s: src/viwmfs.c.s
.PHONY : src/viwmfs.s

# target to generate assembly for a file
src/viwmfs.c.s:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/viwmfs.c.s
.PHONY : src/viwmfs.c.s

src/wmfs.o: src/wmfs.c.o
.PHONY : src/wmfs.o

# target to build an object file
src/wmfs.c.o:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/wmfs.c.o
.PHONY : src/wmfs.c.o

src/wmfs.i: src/wmfs.c.i
.PHONY : src/wmfs.i

# target to preprocess a source file
src/wmfs.c.i:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/wmfs.c.i
.PHONY : src/wmfs.c.i

src/wmfs.s: src/wmfs.c.s
.PHONY : src/wmfs.s

# target to generate assembly for a file
src/wmfs.c.s:
	$(MAKE) -f CMakeFiles/wmfs.dir/build.make CMakeFiles/wmfs.dir/src/wmfs.c.s
.PHONY : src/wmfs.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... wmfs"
	@echo "... src/barwin.o"
	@echo "... src/barwin.i"
	@echo "... src/barwin.s"
	@echo "... src/cfactor.o"
	@echo "... src/cfactor.i"
	@echo "... src/cfactor.s"
	@echo "... src/client.o"
	@echo "... src/client.i"
	@echo "... src/client.s"
	@echo "... src/color.o"
	@echo "... src/color.i"
	@echo "... src/color.s"
	@echo "... src/config.o"
	@echo "... src/config.i"
	@echo "... src/config.s"
	@echo "... src/draw.o"
	@echo "... src/draw.i"
	@echo "... src/draw.s"
	@echo "... src/event.o"
	@echo "... src/event.i"
	@echo "... src/event.s"
	@echo "... src/ewmh.o"
	@echo "... src/ewmh.i"
	@echo "... src/ewmh.s"
	@echo "... src/frame.o"
	@echo "... src/frame.i"
	@echo "... src/frame.s"
	@echo "... src/infobar.o"
	@echo "... src/infobar.i"
	@echo "... src/infobar.s"
	@echo "... src/init.o"
	@echo "... src/init.i"
	@echo "... src/init.s"
	@echo "... src/launcher.o"
	@echo "... src/launcher.i"
	@echo "... src/launcher.s"
	@echo "... src/layout.o"
	@echo "... src/layout.i"
	@echo "... src/layout.s"
	@echo "... src/menu.o"
	@echo "... src/menu.i"
	@echo "... src/menu.s"
	@echo "... src/mouse.o"
	@echo "... src/mouse.i"
	@echo "... src/mouse.s"
	@echo "... src/parse.o"
	@echo "... src/parse.i"
	@echo "... src/parse.s"
	@echo "... src/parse_api.o"
	@echo "... src/parse_api.i"
	@echo "... src/parse_api.s"
	@echo "... src/screen.o"
	@echo "... src/screen.i"
	@echo "... src/screen.s"
	@echo "... src/split.o"
	@echo "... src/split.i"
	@echo "... src/split.s"
	@echo "... src/status.o"
	@echo "... src/status.i"
	@echo "... src/status.s"
	@echo "... src/systray.o"
	@echo "... src/systray.i"
	@echo "... src/systray.s"
	@echo "... src/tag.o"
	@echo "... src/tag.i"
	@echo "... src/tag.s"
	@echo "... src/util.o"
	@echo "... src/util.i"
	@echo "... src/util.s"
	@echo "... src/viwmfs.o"
	@echo "... src/viwmfs.i"
	@echo "... src/viwmfs.s"
	@echo "... src/wmfs.o"
	@echo "... src/wmfs.i"
	@echo "... src/wmfs.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

